
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trainingcode
    username: trainingcode
    password: trainingcode
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # cré le schema lorsque l'appli est lancé et le détruit lorsque qu'on stop uniquement pour les tuto jamais en prod pour ne pas dropper les data
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        enable_lazy_load_no_trans: true

# spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true